version: '3'
  
services:
  
    toxsense_php:
        build:
            context: ./docker/php
        expose:
            - 9000
        volumes:
            - ./html:/var/www/
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        restart: unless-stopped
        environment:
            MYSQL_HOST: toxsense_db
            MYSQL_DATABASE: toxsense
            MYSQL_USER: toxsense
            MYSQL_PASSWORD: JSrGPYEWaQC6yFWEFWhDV3dzzThwfhVEaFc
  
    toxsense_nginx:
        image: nginx:latest
        expose:
            - 80
        volumes:
            - ./html:/var/www/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        restart: unless-stopped
        depends_on:
            - toxsense_php
        environment:
            VIRTUAL_HOST: toxsense.de
            LETSENCRYPT_HOST: toxsense.de
  
    toxsense_db:
        image: mysql:latest
        expose:
            - 3306
        volumes:
            - ./docker/mysql/db:/var/lib/mysql
        depends_on:
            - toxsense_php
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
            MYSQL_DATABASE: toxsense
            MYSQL_USER: toxsense
            MYSQL_PASSWORD: JSrGPYEWaQC6yFWEFWhDV3dzzThwfhVEaFc
        restart: unless-stopped
    
    toxsense_api:
        build: ./docker/api
        expose:
            - 80
        volumes:
            - ./api:/app
        depends_on:
            - toxsense_db
        environment:
            VIRTUAL_HOST: api.toxsense.de
            LETSENCRYPT_HOST: api.toxsense.de
            MYSQL_HOST: toxsense_db
            MYSQL_DATABASE: toxsense
            MYSQL_USER: toxsense
            MYSQL_PASSWORD: JSrGPYEWaQC6yFWEFWhDV3dzzThwfhVEaFc
        restart: unless-stopped
        
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        restart: unless-stopped
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - ./nginx-proxy/certs:/etc/nginx/certs:ro
          - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
          - ./nginx-proxy/html:/usr/share/nginx/html
          - ./nginx-proxy/conf.d:/etc/nginx/conf.d
        environment:
          - ENABLE_IPV6=true
    nginx-proxy-letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: nginx-proxy-letsencrypt
        volumes:
          - ./nginx-proxy/certs:/etc/nginx/certs:rw
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - ./nginx-proxy/acme.sh:/etc/acme.sh
        volumes_from:
          - nginx-proxy
        environment:
          - DEFAULT_EMAIL=s1@bilhoefer.de
        restart: unless-stopped

        
networks:
  default:
    external:
      name: nginx-proxy
